{{- if .Values.certificate }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.certicate.namespace }}
spec:
  secretName: {{ .Values.certificate.name }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef }}
    kind: {{ .Values.certificate.issuerKind }}
  dnsNames: 
    - {{ .Values.certificate.dnsNames }}
{{- end }}
