{{- if .Values.secrets }}
{{- range $key := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  cert-manager-secret: {{ .secret }}
{{- end }}
{{- end }}
